In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

### MNIST 데이터셋 로딩
트레인셋 60,000개 테스트셋 10,000개로 분리
레이블은 자동으로 one-hot 엔코딩 처리됨

In [7]:
mnist = keras.datasets.mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

X_train 데이터는 28x28 이미지 데이터가 60000개 있음 <br/>
데이터를 1차원 벡터로 변환 (60000, 784)

In [8]:
#X_train reshape
X_train = X_train / 255.0
X_train = X_train.reshape(-1, 28*28)

In [9]:
X_train.dtype

dtype('float64')

In [10]:
X_train.shape

(60000, 784)

In [11]:
#X_test reshape
X_test = X_test / 255.0
X_test = X_test.reshape(-1, 28*28)

In [12]:
X_train = X_train.astype('float32')
X_train.dtype

dtype('float32')

In [13]:
X_test = X_test.astype('float32')
X_test.dtype

dtype('float32')

In [14]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [15]:
# X_train, X_test [0, 1] 사이의 값으로 정규화 (Normalization)


In [16]:
# One-hot encoding
Y_train = tf.keras.utils.to_categorical(Y_train, 10)
Y_test = tf.keras.utils.to_categorical(Y_test, 10)

### 모델 만들기
입력층과 출력층 두 개의 층을 가진 네트워크 (v1)<br/>
입력층 - 히든층 - 히든층 - 출력층 (v2)<br/>
입력층 - 히든층 - Dropout - 히든층 - Dropout - 출력층 (v3)<br/>


In [22]:
#활성화함수 relu, softmax 적용, Dropout 적용
model = keras.Sequential()
model.add(keras.layers.Dense(100, activation='relu', input_shape=(784,)))
model.add(keras.layers.Dropout(0.3))
model.add(keras.layers.Dense(100, activation='relu'))
model.add(keras.layers.Dropout(0.3))
model.add(keras.layers.Dense(10, activation='softmax'))

In [23]:
# 모델 요약보기
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 100)               78500     
                                                                 
 dropout_2 (Dropout)         (None, 100)               0         
                                                                 
 dense_4 (Dense)             (None, 100)               10100     
                                                                 
 dropout_3 (Dropout)         (None, 100)               0         
                                                                 
 dense_5 (Dense)             (None, 10)                1010      
                                                                 
Total params: 89,610
Trainable params: 89,610
Non-trainable params: 0
_________________________________________________________________


In [24]:
# 모델 컴파일
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics='accuracy')

In [25]:
# 모델 학습 시키기
model.fit(X_train, Y_train, epochs=20, verbose=0)

In [26]:
# 모델 평가
model.evaluate(X_test, Y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0780 - accuracy: 0.9785


[0.07798787206411362, 0.9785000085830688]

In [27]:
# 예측 수행
model.predict(X_train[0:1])

array([[1.3149943e-24, 1.2518192e-13, 7.9726520e-17, 8.7251328e-03,
        2.8998856e-19, 9.9127483e-01, 1.4508682e-20, 1.2291587e-19,
        1.7366991e-14, 1.3498115e-09]], dtype=float32)

In [30]:
print(np.argmax(model.predict(X_train[0:1]), axis=-1))
print(Y_train[0])

[5]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
